package com.oyxdsg.smartmaid.entity.ai;

/**
 * Maid jump offline precise solution table (generated by tools/gen_jump_table.js, do not edit).
 *
 * For each scenario (horizontal feet displacement dist x height diff dy) the safe takeoff
 * solution is precomputed: {sprint: walk/sprint tier, back: takeoff-point retreat from edge}.
 * The mod only looks up the table at runtime; no physics computation in-game.
 *
 * Physics: prismarine-physics (vanilla), MOVEMENT_SPEED=0.16,
 * vy0=0.42 max rise ~1.25 blocks, airborne continuous-forward input (+0.02/tick).
 */
public final class MaidJumpTable {

    /** Jump solution: sprint = sprint tier, back = takeoff-point retreat (blocks) */
    public record JumpSolution(boolean sprint, double back) {}

    private static final JumpSolution[] TABLE = new JumpSolution[40];

    private static void put(int dist, int dy, JumpSolution s) {
        TABLE[dist * 8 + (dy + 3)] = s;
    }

    static {
        put(2, -3, new JumpSolution(false, 1.25));
        put(2, -2, new JumpSolution(false, 1.25));
        put(2, -1, new JumpSolution(false, 1.25));
        put(2, 0, new JumpSolution(false, 1.25));
        put(2, 1, new JumpSolution(false, 0));
        put(3, -3, new JumpSolution(false, 0.25));
        put(3, -2, new JumpSolution(false, 0.25));
        put(3, -1, new JumpSolution(false, 0.25));
        put(3, 0, new JumpSolution(false, 0.25));
        put(3, 1, new JumpSolution(false, 0));
        put(4, -3, new JumpSolution(false, 0));
        put(4, -2, new JumpSolution(false, 0));
        put(4, -1, new JumpSolution(false, 0));
        put(4, 0, new JumpSolution(true, 1.25));
        put(4, 1, new JumpSolution(true, 0));
    }

    /**
     * Look up the jump solution for scenario (dist, dy); null if unsolvable.
     */
    public static JumpSolution get(int dist, int dy) {
        if (dist < 2 || dist > 4 || dy < -3 || dy > 1) {
            return null;
        }
        return TABLE[dist * 8 + (dy + 3)];
    }
}
