// Generates MaidJumpTable.java — offline precise jump solution table for the maid.
// Physics: prismarine-physics (vanilla-equivalent). MOVEMENT_SPEED=0.16.
// Scenarios: horizontal feet displacement dist in {2,3,4} x height diff dy in {-3..+1}.
// Solution: {sprint, back} where sprint = walk/sprint tier, back = takeoff-point retreat from edge.
// NOTE: takeoff speed is FIXED (no run-up needed) — capability equals vanilla player jumps.
// Run: node tools/gen_jump_table.js
const SPRINT_MULT = 1.3
const BOOST = 0.2            // sprint jump horizontal impulse (not used directly; fixed takeoff below)
const INERTIA = 0.91
const ACCEL = 0.02           // airborne continuous-forward acceleration
const EDGE_INSET = 0.1       // takeoff inset from block edge
const LAND_TOL = 0.1

// FIXED takeoff speeds (no run-up). Run tier covers all scenarios incl. gap-3 + up-1.
const TAKEOFF_WALK = 0.30     // blocks/tick
const TAKEOFF_RUN = 0.55      // blocks/tick

// MC vertical order: displacement before gravity
function traj (takeoff) {
  let v = takeoff, x = 0, y = 0, vy = 0.42, pts = []
  for (let t = 0; t < 40; t++) {
    x += v; y += vy
    pts.push({ x, y })
    v = v * INERTIA + ACCEL
    vy = (vy - 0.08) * 0.98
    if (y <= 0 && t > 0) break
  }
  return pts
}

// From takeoff point (relative 0,0), can the jump cross the far edge (needNear) with height dy?
function canLand (needNear, dy, takeoff) {
  const pts = traj(takeoff)
  for (const p of pts) {
    if (p.x >= needNear && p.y >= dy - LAND_TOL) return true
  }
  return false
}

// Solve: walk tier then sprint tier; retreat (back) until the landing lands in the target cell
// (or, for up-jumps, the trajectory crosses the target cell at sufficient height).
function solve (dist, dy) {
  for (const sprint of [false, true]) {
    const takeoff = sprint ? TAKEOFF_RUN : TAKEOFF_WALK
    for (let back = 0; back <= 3.001; back += 0.25) {
      // horizontal distance from takeoff point to target cell center = dist - 0.4 + back
      const L = dist - (0.5 - EDGE_INSET) + back
      const needNear = L - 0.5
      const needFar = L + 0.5
      const pts = traj(takeoff)
      const landX = pts[pts.length - 1].x
      if (dy > 0) {
        // up-jump: some trajectory point crosses the target cell with height >= dy (collides with platform)
        if (pts.some(p => p.x >= needNear && p.x <= needFar && p.y >= dy - LAND_TOL)) {
          return { sprint, back: Math.round(back * 100) / 100 }
        }
      } else {
        // flat / down-jump: landing point falls in the target cell, and height reachable
        if (landX >= needNear && landX <= needFar &&
            pts.some(p => p.x >= needNear && p.y >= dy - LAND_TOL)) {
          return { sprint, back: Math.round(back * 100) / 100 }
        }
      }
    }
  }
  return null
}

const lines = []
lines.push('package com.oyxdsg.smartmaid.entity.ai;')
lines.push('')
lines.push('/**')
lines.push(' * Maid jump offline precise solution table (generated by tools/gen_jump_table.js, do not edit).')
lines.push(' *')
lines.push(' * For each scenario (horizontal feet displacement dist x height diff dy) the safe takeoff')
lines.push(' * solution is precomputed: {sprint: walk/sprint tier, back: takeoff-point retreat from edge}.')
lines.push(' * The mod only looks up the table at runtime; no physics computation in-game.')
lines.push(' *')
lines.push(' * Physics: prismarine-physics (vanilla), MOVEMENT_SPEED=0.16,')
lines.push(' * vy0=0.42 max rise ~1.25 blocks, airborne continuous-forward input (+0.02/tick).')
lines.push(' */')
lines.push('public final class MaidJumpTable {')
lines.push('')
lines.push('    /** Jump solution: sprint = sprint tier, back = takeoff-point retreat (blocks) */')
lines.push('    public record JumpSolution(boolean sprint, double back) {}')
lines.push('')
lines.push('    private static final JumpSolution[] TABLE = new JumpSolution[40];')
lines.push('')
lines.push('    private static void put(int dist, int dy, JumpSolution s) {')
lines.push('        TABLE[dist * 8 + (dy + 3)] = s;')
lines.push('    }')
lines.push('')
lines.push('    static {')

let count = 0
let unsolvable = []
for (const dist of [2, 3, 4]) {
  for (let dy = -3; dy <= 1; dy++) {
    const s = solve(dist, dy)
    if (s) {
      lines.push(`        put(${dist}, ${dy}, new JumpSolution(${s.sprint}, ${s.back}));`)
      count++
    } else {
      unsolvable.push(`(${dist},${dy})`)
    }
  }
}

lines.push('    }')
lines.push('')
lines.push('    /**')
lines.push('     * Look up the jump solution for scenario (dist, dy); null if unsolvable.')
lines.push('     */')
lines.push('    public static JumpSolution get(int dist, int dy) {')
lines.push('        if (dist < 2 || dist > 4 || dy < -3 || dy > 1) {')
lines.push('            return null;')
lines.push('        }')
lines.push('        return TABLE[dist * 8 + (dy + 3)];')
lines.push('    }')
lines.push('}')
lines.push('')

const fs = require('fs')
const path = require('path')
const out = path.join(__dirname, '..', 'src', 'main', 'java', 'com', 'oyxdsg', 'smartmaid', 'entity', 'ai', 'MaidJumpTable.java')
fs.writeFileSync(out, lines.join('\n'), 'utf8')
console.error(`[gen] written ${out}: ${count} solutions; unsolvable: ${unsolvable.length ? unsolvable.join(', ') : 'none (all covered)'}`)
